pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                script {
                    // Checkout the 'main' branch from your repository
                    git branch: 'main', url: 'https://github.com/agnishwarr/DevopsP53.git'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                // Change directory and build the Docker image in the same shell invocation
                bat '''
                    cd demodocker
                    docker build -t my_app:1.0 .
                '''
            }
        }
        stage('Deploy') {
            steps {
                // Change directory and run docker-compose in the same shell invocation
                bat '''
                    cd demodocker
                    docker-compose up -d
                '''
            }
        }
    }
}
